---
name: build avd devcontainer for docker pull

env:
  _AVD_VERSION: "4.1.0"
  # to avoid unknown/unknown image build
  # check following thread for the details:
  #   https://github.com/orgs/community/discussions/45969
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

on:
  push:
    branches:
      - master

jobs:
  build_container_image:
    runs-on: ubuntu-22.04
    steps:
      # checkout the repo
      - name: Checkout
        uses: actions/checkout@v3
      # setup qemu
      - name: setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/arm64/v8,linux/amd64"
      # setup buildx
      - name: setup buildX
        uses: docker/setup-buildx-action@v2
      # login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # generate docker tags and labels
      - name: Generate Docker tags and labels
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ankudinov/avd-devcontainer/avd-devcontainer
          tags: |
            type=raw,value=latest
            type=raw,value=avd-test-devcontainer
      # build and push the image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .devcontainer
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64/v8,linux/amd64
          provenance: false
      # delete old images
      - name: Delete old containers
        uses: actions/delete-package-versions@v4
        with:
          package-name: avd-devcontainer/avd-devcontainer
          package-type: container
          min-versions-to-keep: 1
          token: ${{ secrets.GITHUB_TOKEN }}
