---
name: build-dev

env:
  _AVD_VERSION: "4.1.0"
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

on:
  workflow_run:
    workflows: [ build-base ]
    types: [ completed ]

jobs:
  build_dev_image:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:

      - name: Starting container build
        run: echo "Starting container build. Be patient. 🐢"

      - name: Checkout code ✅
        uses: actions/checkout@v3

      - name: Check if avd-base needs to be built 🤔
        uses: dorny/paths-filter@v2
        id: filter-avd-dev
        with:
          filters: |
            workflows:
              - 'avd-containers/dev/.devcontainer/**'
              - '.github/workflows/**'

      - name: setup QEMU for multi-arch builds 🏗️
        if: steps.filter-avd-dev.outputs.workflows == 'true'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/arm64/v8,linux/amd64"

      - name: setup Docker buildX for multi-arch builds 🏗️
        if: steps.filter-avd-dev.outputs.workflows == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub 🗝️
        if: steps.filter-avd-dev.outputs.workflows == 'true'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image 🔨
        if: steps.filter-avd-dev.outputs.workflows == 'true'
        uses: devcontainers/ci@v0.3
        with:
          subFolder: avd-containers/base
          imageName: ghcr.io/ankudinov/avd-devcontainer/dev
          imageTag: latest,v${{ env._AVD_VERSION }}
          platform: linux/arm64,linux/amd64
          push: always
