---
name: build-all-containers

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

on:
  push:
    branches:
      - master

jobs:

  build_base:

    uses: ./.github/workflows/container_build_template.yml

    strategy:
      matrix:
        container: [base]
        username: [vscode]
        include:
          - container: base
            tags: latest,3.11-slim-bullseye-rev0.1
            platform: linux/arm64/v8,linux/amd64
            from_image: python
            from_variant: 3.11-slim-bullseye
            user_id: 1000
            group_id: 1000

    with:
      container_name: ${{ matrix.container }}
      container_tags: ${{ matrix.tags }}
      platform: ${{ matrix.platform }}
      from_image: ${{ matrix.from_image }}
      from_variant: ${{ matrix.from_variant }}
      username: ${{ matrix.username }}
      user_id: ${{ matrix.user_id }}
      group_id: ${{ matrix.group_id }}

  build_all_containers:

    needs: [build_base]

    uses: ./.github/workflows/container_build_template.yml

    strategy:
      matrix:
        container: [dev, universal]
        username: [vscode]
        include:
          - container: dev
            tags: latest,3.11-slim-bullseye-rev0.1
            platform: linux/arm64/v8,linux/amd64
            from_image: ghcr.io/ankudinov/avd-devcontainer/base
            from_variant: 3.11-slim-bullseye-rev0.1
          - container: universal
            tags: latest,3.11-slim-bullseye-avd4.1.0-rev0.1
            avd_version: "4.1.0"
            platform: linux/arm64/v8,linux/amd64
            from_image: ghcr.io/ankudinov/avd-devcontainer/base
            from_variant: 3.11-slim-bullseye-rev0.1
            avd_pip_install: "ansible-core>=2.13.1,<2.14.0"

    with:
      container_name: ${{ matrix.container }}
      container_tags: ${{ matrix.tags }}
      platform: ${{ matrix.platform }}
      from_image: ${{ matrix.from_image }}
      from_variant: ${{ matrix.from_variant }}
      avd_version: ${{ matrix.avd_version }}
      avd_pip_install: ${{ matrix.avd_pip_install }}
      username: ${{ matrix.username }}

  # build_all_containers:

  #   needs: [build_base_container]

  #   strategy:
  #     matrix:
  #       container: [ci, dev]
  #       include:
  #         - container: ci
  #           tags: latest,3.11-slim-bullseye-rev0.1
  #           platform: linux/arm64/v8,linux/amd64
  #         - container: dev
  #           tags: latest,3.11-slim-bullseye-rev0.1
  #           platform: linux/arm64/v8,linux/amd64

  #   uses: ./.github/workflows/container_build_template.yml

  #   with:
  #     container_name: ${{ matrix.container }}
  #     container_tags: ${{ matrix.tags }}
  #     platform: ${{ matrix.platform }}

  # build_universal_container:

  #   needs: [build_all_containers]

  #   uses: ./.github/workflows/container_build_template.yml

  #   strategy:
  #     matrix:
  #       container: [universal]
  #       include:
  #         - container: universal
  #           tags: latest,3.11-slim-bullseye-avd4.1.0-rev0.1
  #           platform: linux/arm64/v8,linux/amd64

  #   with:
  #     container_name: ${{ matrix.container }}
  #     container_tags: ${{ matrix.tags }}
  #     platform: ${{ matrix.platform }}
