---
name: build-all-containers

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

on:
  push:
    branches:
      - master

jobs:

  build_base:

    uses: ./.github/workflows/container_build_template.yml

    strategy:
      matrix:
        container: [base]
        include:
          - container: base
            python_version: 3.11

    with:
      container_name: ${{ matrix.container }}
      container_tags: latest,${{ matrix.from_variant }}-rev0.1
      username: ${{ matrix.username }}
      user_id: ${{ matrix.user_id }}
      group_id: ${{ matrix.group_id }}
      python_version: ${{ matrix.python_version }}

  build_all_containers:

    needs: [build_base]

    uses: ./.github/workflows/container_build_template.yml

    strategy:
      matrix:
        container: [dev, universal]
        include:
          - container: dev
            tags: latest,3.11-slim-bullseye-rev0.1
            python_version: 3.11
          - container: universal
            tags: latest,3.11-slim-bullseye-avd4.1.0-rev0.1
            avd_version: "4.1.0"
            python_version: 3.11
            avd_pip_install: "ansible-core>=2.13.1,<2.14.0"

    with:
      container_name: ${{ matrix.container }}
      container_tags: ${{ matrix.tags }}
      avd_version: ${{ matrix.avd_version }}
      avd_pip_install: ${{ matrix.avd_pip_install }}
      username: ${{ matrix.username }}
      python_version: ${{ matrix.python_version }}

  # build_all_containers:

  #   needs: [build_base_container]

  #   strategy:
  #     matrix:
  #       container: [ci, dev]
  #       include:
  #         - container: ci
  #           tags: latest,3.11-slim-bullseye-rev0.1
  #           platform: linux/arm64/v8,linux/amd64
  #         - container: dev
  #           tags: latest,3.11-slim-bullseye-rev0.1
  #           platform: linux/arm64/v8,linux/amd64

  #   uses: ./.github/workflows/container_build_template.yml

  #   with:
  #     container_name: ${{ matrix.container }}
  #     container_tags: ${{ matrix.tags }}
  #     platform: ${{ matrix.platform }}

  # build_universal_container:

  #   needs: [build_all_containers]

  #   uses: ./.github/workflows/container_build_template.yml

  #   strategy:
  #     matrix:
  #       container: [universal]
  #       include:
  #         - container: universal
  #           tags: latest,3.11-slim-bullseye-avd4.1.0-rev0.1
  #           platform: linux/arm64/v8,linux/amd64

  #   with:
  #     container_name: ${{ matrix.container }}
  #     container_tags: ${{ matrix.tags }}
  #     platform: ${{ matrix.platform }}
