---
name: build-all-containers

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

on:
  push:
    branches:
      - master

jobs:

  build_base:

    uses: ./.github/workflows/container_build_template.yml

    strategy:
      matrix:
        container: [base]
        include:
          - container: base
            python_version: 3.11

    with:
      container_name: ${{ matrix.container }}
      python_version: ${{ matrix.python_version }}

  build_all_containers:

    needs: [build_base]

    uses: ./.github/workflows/container_build_template.yml

    strategy:
      matrix:
        container: [dev, universal]
        include:
          - container: dev
            python_version: 3.11
          - container: universal
            avd_version: "4.1.0"
            python_version: 3.11
            avd_pip_install: "ansible-core>=2.13.1,<2.14.0"

    with:
      container_name: ${{ matrix.container }}
      avd_version: ${{ matrix.avd_version }}
      avd_pip_install: ${{ matrix.avd_pip_install }}
      python_version: ${{ matrix.python_version }}
